### ISSUE TITLE
Preinstall Wine by default on VM3

### ISSUE THREAD

**Issue by upintheairsheep** [computernewb/collabvm-1.2.ts#22]
Please consider installing Wine by default on VM3. Waydroid could be installed as well if it could if you want to see many people play around with Android apps without having to make an Android VM.

**Comment by elijahr2411** [comment]
Hi,

This is the repository for the CollabVM server software, and is not for suggestions for the VMs themselved on the CollabVM website. Please consider joining our Discord server and leaving your suggestions in the appropriate channel there, or emailing us at staff(at)computernewb.com

Thank you
