### ISSUE TITLE
VM9?

### ISSUE THREAD

**Issue by upintheairsheep** [computernewb/collabvm-1.2.ts#23]
Would be interesting to see any version of Mac OS/OS X/macOS as VM9 to get the full trinity. You could hold up votes for the specific version to choose, but it should either be any classic macOS, Mac OS Tiger on PowerPC as it is the last version on it's design and can run both Mac OS X and Mac OS Classic apps (though panther is faster at running classic apps), Mac OS X Snow Leopard, Mac OS X Mountain Lion, OS X Mojave, macOS Big Sur (x86), or the current macOS version (on x86, but current macOS on x86 is very boring), or alternate between them.

**Comment by modeco80** [comment]
Closing, for reasoning see #22
