### ISSUE TITLE
how to host collabvm bot on vps

### ISSUE THREAD

**Issue by 1tbfree** [computernewb/collabvm-1.2.ts#24]
you guys block hosting ips

**Comment by elijahr2411** [comment]
Hi,

Firstly, this issues page is for bugs of the CollabVM server software itself. In the future, for questions like yours, please email us at staff(at)computernewb(dot)com

To run a bot on CollabVM, you need to have your account approved for developer status. Instructions for that are [here.](https://computernewb.com/wiki/Creating_a_Bot_for_CollabVM)

After being approved, you can reply to the email you received asking us to whitelist your VPS IP.
