### ISSUE TITLE
Too hard to setup 

### ISSUE THREAD

**Issue by 1tbfree** [computernewb/collabvm-1.2.ts#33]
Before you just needed qemu + node + npm.
Now it does need something you do NOT even need. Why tf do u add some weird stuff to compiling?
It should also have a install script. I can tell that CollabVM 2.0 is best version ever because of that

**Comment by elijahr2411** [comment]
Hello,

If you cannot follow instructions that are (in my opinion) elegantly laid out in the [appropriate guide](https://computernewb.com/wiki/UserVM_Handbook) (or were unable to locate said guide), I suggest not hosting public internet-connected VMs on the internet that anyone can access and use.

Have a nice day.
