### ISSUE TITLE
vmware and windows support

### ISSUE THREAD

**Issue by W-i-n-7** [computernewb/collabvm-1.2.ts#6]
i have a server running windows on bare metal and i dont want to do vm ception to run a collabvm so vmware support would be nice

**Comment by elijahr2411** [comment]
the server already supports windows so you could do QEMU using either HAXM or WHPX. VMWare support may be added in the future but it most likely won't be anytime soon. You're welcome to implement it yourself.

**Comment by W-i-n-7** [comment]
thanks

ma 31. heinäk. 2023 klo 17.55 Elijah R ***@***.***> kirjoitti:
